#!/usr/bin/env python3
"""
Test LLM Integration with Real API Key
"""

from linkedin_agent import UserProfile, JobPosting
from llm_demo import EnhancedLinkedInAgent
import os
from dotenv import load_dotenv

# Load API key from .env
load_dotenv()

print("\n" + "="*70)
print("🤖 TESTING LLM INTEGRATION WITH REAL OPENAI API")
print("="*70)

# Test profile
profile = UserProfile(
    name='Sarah Chen',
    current_role='Frontend Developer',
    years_experience=4,
    skills=['JavaScript', 'React', 'CSS', 'HTML', 'Git'],
    previous_roles=['Junior Developer', 'Intern'],
    education='BS Computer Science',
    certifications=['Google Cloud Associate']
)

# Test job
job = JobPosting(
    title='Senior Frontend Engineer',
    company='TechCorp',
    description='Lead frontend development for scalable web apps',
    required_skills=['JavaScript', 'React', 'CSS', 'TypeScript'],
    preferred_skills=['Next.js', 'Testing', 'DevOps'],
    experience_years=5,
    seniority_level='Senior'
)

# Create agent with LLM
print("\n🤖 Creating Enhanced Agent with LLM...")
agent = EnhancedLinkedInAgent(profile, use_llm=True)

if agent.llm_available:
    print("✅ LLM IS ENABLED - Using OpenAI GPT!")
else:
    print("⚠️  LLM not available")
    exit(1)

print("\n📊 Analyzing job with AI...")
print("(This will take a few seconds as it calls OpenAI API...)\n")

try:
    analysis = agent.analyze_job_posting(job, include_llm=True)
    
    print(f"\n✓ Match Score: {analysis['match_score']['percentage']}%")
    print(f"✓ Rating: {analysis['match_score']['rating']}")
    
    if 'llm_enhanced' in analysis:
        print("\n" + "="*70)
        print("🤖 AI-POWERED RESPONSES (GENERATED BY GPT)")
        print("="*70)
        
        print("\n📝 PERSONALIZED COVER LETTER:")
        print("-" * 70)
        print(analysis['llm_enhanced']['personalized_cover_letter'])
        
        print("\n🎤 AI INTERVIEW TALKING POINTS:")
        print("-" * 70)
        for i, point in enumerate(analysis['llm_enhanced']['ai_interview_points'], 1):
            print(f"  {i}. {point}")
        
        print("\n📊 JOB FIT NARRATIVE:")
        print("-" * 70)
        print(analysis['llm_enhanced']['fit_narrative'])
        
        print("\n🏢 COMPANY RESEARCH BRIEF:")
        print("-" * 70)
        print(analysis['llm_enhanced']['company_research'])
        
        print("\n" + "="*70)
        print("✅ SUCCESS! LLM is working perfectly with real OpenAI API!")
        print("="*70 + "\n")

except Exception as e:
    print(f"❌ Error: {e}")
    import traceback
    traceback.print_exc()
    exit(1)
